name: Flaky Test Detector (Jest)

on:
  workflow_dispatch:
  pull_request:

jobs:
  detect-flaky-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        iteration: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests and collect results
        run: |
          mkdir -p test-results
          npm test || true
        env:
          JEST_JUNIT_OUTPUT_NAME: results-${{ matrix.iteration }}.xml

      - name: Rename JUnit XML for iteration
        run: mv test-results/results.xml test-results/results-${{ matrix.iteration }}.xml

      - name: Upload test result
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.iteration }}
          path: test-results/results-${{ matrix.iteration }}.xml

  analyze-results:
    runs-on: ubuntu-latest
    needs: detect-flaky-tests

    steps:
      - name: Checkout flaky analysis script repo
        uses: actions/checkout@v4
        with:
          repository: jiz17043/detect_flaky

      - name: Download all test results
        uses: actions/download-artifact@v4
        with:
          path: all-results

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install required libraries
        run: pip install lxml

      - name: Detect flaky tests
        run: |
          python scripts/detect_flaky_tests.py
